mainproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import quiz
from quiz import classviews,views
from django.contrib.auth import urls as auth_urls


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'quiz/',include('quiz.urls')),
    # auth and authz
    url(r'^logout/', quiz.views.logoutuser, name='logout'),
    url(r'^signup/$', classviews.UserSignInView.as_view(), name='signup'),
    url(r'^', include(auth_urls)),
    url(r'^$',quiz.views.index,name='index')
]

quiz/urls.py
from django.conf.urls import url, include

import quiz
from quiz import views, classviews

urlpatterns=[


    url(r'home/',view=classviews.ExamListView.as_view(),name='home'),
    url(r'newexam/',view=classviews.ExamCreateView.as_view(),name='newexam'),
    url(r'editexam/(?P<pk>[0-9]+)',view=classviews.ExamUpdateView.as_view(),name='editexam'),
    url(r'deleteexam/(?P<pk>[0-9]+)',view=classviews.ExamDeleteView.as_view(),name='deleteexam'),

    # here the primary key refers to the foreign key of the exam to which the question belongs to
    url(r'newquestion/(?P<pk>[0-9]+)',view=classviews.QuestionCreateView.as_view(),name='newquestion'),
    url(r'changequestions/(?P<pk>[0-9]+)',view=classviews.QuestionsEditView.as_view(),name='changequestions'),
    # here the primary key refers to the ID of itself
    url(r'editquestion/(?P<pk>[0-9]+)',view=classviews.QuestionEditView.as_view(),name='editquestion'),
    url(r'deletequestion/(?P<pk>[0-9]+)',view=classviews.QuestionDeleteView.as_view(),name='deletequestion'),
    url(r'allquestions',view=classviews.QuestionListView.as_view(),name='allquestions'),

    url(r'write/(?P<pk>[0-9]+)',view=classviews.WriteExam.as_view(),name='write'),
]

quiz/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Exam(models.Model):
    name=models.CharField(max_length=50)
    length=models.PositiveIntegerField()
    questioncount=models.IntegerField(default=0)
    user=models.ForeignKey(User,default=None)
    def __unicode__(self):
        return self.name

class Question(models.Model):
    text=models.CharField(max_length=100)
    correctoption=models.PositiveSmallIntegerField()
    option1=models.CharField(max_length=50)
    option2=models.CharField(max_length=50)
    option3=models.CharField(max_length=50)
    option4=models.CharField(max_length=50)
    exam=models.ForeignKey(Exam)

    def __unicode__(self):
        return self.text

quiz/forms.py
from django import forms
from django.contrib.auth.models import User

from quiz.models import Exam, Question


class ExamForm(forms.ModelForm):
    class Meta:
        model=Exam
        fields=['name','length','questioncount']


class QuestionForm(forms.ModelForm):
    option1=forms.ChoiceField()
    option2=forms.ChoiceField()
    option3=forms.ChoiceField()
    option4=forms.ChoiceField()

    class Meta:
        model=Question
        fields=['text','option1','option2','option3','option4','correctoption','exam']


class Userform(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model=User
        fields=['username','email','first_name','last_name','password']

quiz/views.py
from django.contrib.auth import logout
from django.forms.formsets import formset_factory
from django.http.response import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from quiz.forms import ExamForm, QuestionForm


def index(request):
    return HttpResponse(render(request,template_name='index.html'))

def logoutuser(request):
    logout(request)
    return redirect('/login/')

templates/allquestions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Questions</title>
</head>
<body>
<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Quiz Master</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a class="button" href="{% url 'logout' %}">Logout</a></li>
      </ul>
    </div>
  </nav>

<ul>
{% for question in object_list %}
   <li>{{ question }}</li>
    <ol style="list-style: decimal">
        <li>{{ question.option1 }}</li>
        <li>{{ question.option2 }}</li>
        <li>{{ question.option3 }}</li>
        <li>{{ question.option4 }}</li>
    </ol>
    <span>correct option : {{ question.correctoption }}</span>
    <a href="/quiz/editquestion/{{ question.id }}">Edit Question</a>
    <a href="/quiz/deletequestion/{{ question.id }}">Delete Question</a>
{% endfor %}
</ul>
<a href="/quiz/home">Back Home</a>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Exams</title>
{#    importing css #}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'materialize/css/materialize.css' %}">
    <link rel="script" href="{% static 'materialize/js/materialize.js' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Quiz Master</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a class="button" href="{% url 'logout' %}">Logout</a></li>
      </ul>
    </div>
  </nav>

<div class="container-fluid row ">
{# add an exam button #}
    <div class="col">
        <a title="Add an Exam" class="btn-floating btn-large waves-effect waves-light red" href="/quiz/newexam/"><i class="material-icons">add</i></a>
    </div>
    <div class="container">
        {% for article in object_list %}
            <ul class="collection with-header" title="{{ article }}" style="list-style: none">

                <li class="collection-header"><h5><strong>Title: </strong>{{ article.name|title }}</h5></li>
                <li class="collection-item"><span><i class="tiny material-icons">perm_identity</i> </span> {{ article.user }}</li>
                <li class="collection-item"><span><i class="tiny material-icons">query_builder</i>  {{ article.length }} minutes</span></li>
                <li class="collection-item"><span><i class="tiny material-icons">done</i>  {{ article.questioncount }} marks</span></li>
                <li class="collection-item"><a href="/quiz/write/{{ article.id }}">Write Exam</a></li>
                {% if article.user == user %}
                    <li class="collection-item"><a href="/quiz/editexam/{{ article.id }}">Edit</a> </li>

                    <li class="collection-item"><a href="/quiz/deleteexam/{{ article.id }}">Delete</a> </li>
                    <li class="collection-item"><a href="/quiz/changequestions/{{ article.id }}">Edit Questions</a> </li>

                {% endif %}
            </ul>
        {% endfor %}
    </div>
</div>

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome!</title>
    {#    importing css #}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'materialize/css/materialize.css' %}">
    <link rel="script" href="{% static 'materialize/js/materialize.js' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<div class="jumbotron">
	<div class="container row center">
		<h1>Hey There!</h1>
		<h2>Introducing Quiz Master.</h2>
		<h3>No open leaderboards. No inhibitions.</h3>
        <div class="col l6 center-align">
            <a class="btn center-align" href="/login/">Login</a>
        </div>
        <div class="col l6 center-align">
            <a class="btn center-align" href="/signup/">Sign Up</a>
        </div>
	</div>
</div>
</body>
</html>

templates/quiz/done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>done</title>
    {#    importing css #}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'materialize/css/materialize.css' %}">
    <link rel="script" href="{% static 'materialize/js/materialize.js' %}">
    <link rel="script" href="{% static 'js/jquery.js' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Quiz Master</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a class="button" href="{% url 'logout' %}">Logout</a></li>
      </ul>
    </div>
  </nav>

<div class="container">
<div class="jumbotron">
	<div class="container">
		<h1>Your score is {{ score }}.</h1>
		<p>You attempted {{ attempted }} questions.<br/>Your correctly answered the questions...
        {% for each in correctlyanswered %}
            {{ each }}
        {% endfor %}
        </p>
		<p>
			<a class="btn btn-primary btn-lg" href="/quiz/home/">Back Home</a>

		</p>
	</div>
</div>
</div>
</body>
</html>

templates/quiz/exam_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirm Delete</title>
</head>
<body>
<div style="visibility: hidden">
<form method="post" name="form" >

    {% csrf_token %}

    {{ form.as_p }}


  <button class="hiddendiv" id="submit" type="submit" value="Confirm"></button>
</form>
</div>
<script>
    var a=confirm('Are you sure you want to delete?')
    if(a){
        document.getElementById('submit').click();
    }
    else{
        window.location.replace('/quiz/home/')
    }
</script>
</body>
</html>

templates/quiz/exam_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Exam</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'materialize/css/materialize.css' %}">
    <link rel="script" href="{% static 'materialize/js/materialize.js' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Quiz Master</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a class="button" href="{% url 'logout' %}">Logout</a></li>
      </ul>
    </div>
  </nav>

<div class="jumbotron">
	<div class="container">
		<h3>Edit Exam</h3>
    </div>
</div>

<div class="container"><form method="post">
    {% csrf_token %}
    {{ form }}
    <input class="btn-large" type="submit" value="Submit"/>
</form>
    </div>
</body>
</html>

templates/quiz/newexam.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Exam</title>
    {#    importing css #}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'materialize/css/materialize.css' %}">
    <link rel="script" href="{% static 'materialize/js/materialize.js' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Quiz Master</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a class="button" href="{% url 'logout' %}">Logout</a></li>
      </ul>
    </div>
  </nav>

<div class="jumbotron">
	<div class="container">
		<h3>New Exam</h3>
    </div>
</div>
<div class="container">
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
</div>
</body>
</html>

templates/quiz/newquestion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Question</title>
    {#    importing css #}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'materialize/css/materialize.css' %}">
    <link rel="script" href="{% static 'materialize/js/materialize.js' %}">
    <link rel="script" href="{% static 'js/jquery.js' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Quiz Master</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a class="button" href="{% url 'logout' %}">Logout</a></li>
      </ul>
    </div>
  </nav>

<div class="jumbotron">
	<div class="container">
		<h5>Add a question to your exam!</h5>
	</div>
</div>

<div class="container">
<form class="form" method="post" class="form-switcher">
    {% csrf_token %}

    {{ form.text.label }}: {{ form.text }}
    {{ form.option1.label }}: {{ form.option1 }}
    {{ form.option2.label }}: {{ form.option2 }}
    {{ form.option3.label }}: {{ form.option3 }}
    {{ form.option4.label }}: {{ form.option4 }}
    {{ form.correctoption.label }}: {{ form.correctoption }}
{{ form.exam.label }}:
<div class="input-field">
    <select class="browser-default" id="id_exam" name="exam">
    {% for x,y in form.fields.exam.choices %}
        {% if x|stringformat:"s" ==  examid|stringformat:"s"  %}
            <option value="{{ x }}" selected="selected">{{ y }}</option>
        {% endif %}
    {% endfor %}
    </select>
</div>
    <input class="btn" type="submit" value="Save">
</form>
</div>

</body>
</html>

templates/quiz/question_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirm Delete?</title>
</head>
<body>
<div style="visibility: hidden">
<form method="post" name="form" >

    {% csrf_token %}

    {{ form.as_p }}


  <button class="hiddendiv" id="submit" type="submit" value="Confirm"></button>
</form>
</div>
<script>
    var a=confirm('Are you sure you want to delete?')
    if(a){
        document.getElementById('submit').click();
    }
    else{
        window.location.replace('/quiz/home')
    }
</script>
</body>
</html>

templates/quiz/question_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Question</title>
    {#    importing css #}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'materialize/css/materialize.css' %}">
    <link rel="script" href="{% static 'materialize/js/materialize.js' %}">
    <link rel="script" href="{% static 'js/jquery.js' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Quiz Master</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a class="button" href="{% url 'logout' %}">Logout</a></li>
      </ul>
    </div>
  </nav>

<div class="jumbotron">
	<div class="container">
		<h5>Add a question to your exam!</h5>
	</div>
</div>

<div class="container">
<form class="form" method="post" class="form-switcher">
    {% csrf_token %}

    {{ form.text.label }}: {{ form.text }}
    {{ form.option1.label }}: {{ form.option1 }}
    {{ form.option2.label }}: {{ form.option2 }}
    {{ form.option3.label }}: {{ form.option3 }}
    {{ form.option4.label }}: {{ form.option4 }}
    {{ form.correctoption.label }}: {{ form.correctoption }}
{{ form.exam.label }}:
<div class="input-field">
    <select class="browser-default" id="id_exam" name="exam">
    {% for x,y in form.fields.exam.choices %}
            <option value="{{ x }}" selected="selected">{{ y }}</option>
    {% endfor %}
    </select>
</div>
    <input class="btn" type="submit" value="Save">
</form>
</div>

</body>
</html>

templates/quiz/write.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Take exam</title>
    {% load staticfiles %}
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/json2.js' %}"></script>
    {#    importing css #}
    <link rel="stylesheet" href="{% static 'materialize/css/materialize.css' %}">
    <link rel="script" href="{% static 'materialize/js/materialize.js' %}">
    <link rel="script" href="{% static 'js/jquery.js' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Quiz Master</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a class="button" href="{% url 'logout' %}">Logout</a></li>
      </ul>
    </div>
  </nav>

<form method="post">
    {% csrf_token %}
<div class="questions"></div>
    <input type="submit" formmethod="post" value="Submit"/>
</form>
<script type="text/javascript">
    var sons=eval({{ jsonset|safe }});
    for (var i =0;i<sons.length;i++){
        var newContainer=$('<div class="question"></div>');
        newContainer.append('<ul class="options collection with-header" style="list-style: none"><li class="collection-header"><h4>'+(sons[i].fields.text)+'</h4></li></ul>');
        newContainer.append('<li><input type="radio" value='+1+ ' name="question'+(i+1)+'" id='+sons[i].pk + '1' + ' />'+'<label for='+sons[i].pk+'1>'+sons[i].fields.option1+'</label></li>');
        newContainer.append('<li><input type="radio" value='+2+ ' name="question'+(i+1)+'" id='+sons[i].pk + '2' + ' />'+'<label for='+sons[i].pk+'2>'+sons[i].fields.option2+'</label></li>');
        newContainer.append('<li><input type="radio" value='+3+ ' name="question'+(i+1)+'" id='+sons[i].pk + '3' + ' />'+'<label for='+sons[i].pk+'3>'+sons[i].fields.option3+'</label></li>');
        newContainer.append('<li><input type="radio" value='+4+ ' name="question'+(i+1)+'" id='+sons[i].pk + '4' + ' />'+'<label for='+sons[i].pk+'4>'+sons[i].fields.option4+'</label></li>');
        $('.questions').append(newContainer);
    }
    var my_eval=function () {
        var your=$(".question input:checked");
        var j=0;
        for(var i=0;i<sons.length;i++){
            console.log(your[i].val());
        }
        console.log(your);
    }
</script>

</body>
</html>